spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/voicedb
    username: voice_user
    password: voice_pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: none
  liquibase:
    change-log: classpath:db/changelog_init.xml
    enabled: true
    drop-first: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true


